// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWuIb9SgHWZWjj3omJACnT0IPKv1B0yNg',
    appId: '1:238293545027:web:1186223b662836e84e64f6',
    messagingSenderId: '238293545027',
    projectId: 'admin-98d71',
    authDomain: 'admin-98d71.firebaseapp.com',
    storageBucket: 'admin-98d71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0fkq6abyjefdhHpElYbX4CcX4_FsnmA',
    appId: '1:238293545027:android:08ec0b70bb6bffeb4e64f6',
    messagingSenderId: '238293545027',
    projectId: 'admin-98d71',
    storageBucket: 'admin-98d71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSwWQc3UtWT9gkOi7lSddaqS6-eKOO31I',
    appId: '1:238293545027:ios:faf715f25370b6ae4e64f6',
    messagingSenderId: '238293545027',
    projectId: 'admin-98d71',
    storageBucket: 'admin-98d71.firebasestorage.app',
    iosBundleId: 'com.example.prAdminshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSwWQc3UtWT9gkOi7lSddaqS6-eKOO31I',
    appId: '1:238293545027:ios:faf715f25370b6ae4e64f6',
    messagingSenderId: '238293545027',
    projectId: 'admin-98d71',
    storageBucket: 'admin-98d71.firebasestorage.app',
    iosBundleId: 'com.example.prAdminshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWuIb9SgHWZWjj3omJACnT0IPKv1B0yNg',
    appId: '1:238293545027:web:2a7b7d93622b33144e64f6',
    messagingSenderId: '238293545027',
    projectId: 'admin-98d71',
    authDomain: 'admin-98d71.firebaseapp.com',
    storageBucket: 'admin-98d71.firebasestorage.app',
  );
}
